services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: backend-prd:latest
    container_name: backend-prd
    expose:
      - "8100"
    volumes:
      - .:/code
      - /code/.venv
    depends_on:
      - mongo
      - chroma
    env_file:
      - .env
    networks:
      - autos-network
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8100",
        "--reload",
        "--workers",
        "2"
      ]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-prd
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    environment:
      PASSWORD_BASIC_AUTH: ${PASSWORD_BASIC_AUTH}
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - nginx-certbot:/var/www/certbot
      - ./nginx/conf.d:/etc/nginx/conf.d
      # - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    networks:
      - autos-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - nginx-certbot:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email maciasignacio0@gmail.com --agree-tos --no-eff-email -d autosmvp.samaproject.ar


  mongo:
    image: mongo
    container_name: mongo-prd
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASS}
    ports:
      - "27017:27017"
    networks:
      - autos-network

  chroma:
    image: ghcr.io/chroma-core/chroma
    container_name: chroma-prd
    expose:
      - "8000"
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=FALSE
      - CHROMA_WORKERS=1
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - autos-network

volumes:
  mongo_data:
  chroma_data:
  certbot-etc:
  certbot-var:
  nginx-certbot:


networks:
  autos-network:
    driver: bridge